In [36]:
import numpy as np


In [42]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(type(a))
print(f'Shape: {a.shape}')
print(f"Dtype: {a.dtype}")
print(f"Dimension: {a.ndim}")
print(f"Size: {a.size}")
print(f"Item Size: {a.itemsize}")
print(f"Bytes: {a.nbytes}")
print(f"Flags: {a.flags}")

<class 'numpy.ndarray'>
Shape: (3, 3)
Dtype: int64
Dimension: 2
Size: 9
Item Size: 8
Bytes: 72
Flags:   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [43]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [46]:
np.eye(3)
print(np.eye(3).dtype)

float64


In [47]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [49]:
np.linspace(0, 1, 6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

### Array Operations

In [57]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[0, 1])  # Accessing element at row 0, column 1
print(arr[1:2])  # Accessing element at row 1

2
[[4 5 6]]


In [59]:
print(arr.reshape(3, 2))  # Reshaping to 3 rows and 2 columns
print(arr.T)  # Transposing the array

[[1 2]
 [3 4]
 [5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [62]:
arr.flatten()  # Flattening the array to 1D

array([1, 2, 3, 4, 5, 6])

In [63]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
print(x + y)  # Element-wise addition
print(x - y)  # Element-wise subtraction
print(x * y)  # Element-wise multiplication
print(x / y)  # Element-wise division


[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [73]:
import math
print(arr.sum())  # Sum of all elements
print(arr.max())  # Sum along columns
print(arr.min())  # Sum along rows
print(arr.mean())  # Mean of all elements

21
6
1
3.5
